# Generated by Django 4.0.7 on 2023-05-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
