# Generated by Django 4.0.7 on 2023-05-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('img', models.CharField(blank=True, max_length=200)),
                ('inventory', models.IntegerField()),
                ('price', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
